repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.0.290
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
      types_or: [python, pyi, jupyter]
    - id: ruff-format
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args:
      - --profile
      - black
- repo: https://github.com/asottile/pyupgrade
  rev: v3.11.0
  hooks:
  - id: pyupgrade
    args:
    - --py39-plus
